server:
  port: 10010
hystrix:
  command:
    default:
      execution.isolation.thread.timeoutInMilliseconds: 6000 # 熔断超时时长：6000ms
ribbon:
  ConnectTimeout: 500 # ribbon链接超时时长
  ReadTimeout: 2000 # ribbon读取超时时长

spring:
  application:
    name: ly-gateway

  cloud:
    gateway:
      default-filters: # 默认过滤项
        - StripPrefix=1 # 去除路由前缀
        - name: Hystrix # 指定过滤工厂名称(可以是任意过滤工厂类型)
          args: #指定过滤参数
            name: fallbackmd #hystrix的指令名
            fallbackUri: forward:/hystrix/fallback #失败后的跳转页面
        - name: RequestRateLimiter #请求限流 名字不能乱写
          args:
            key-resolver: "#{@ipKeyResolver}" # 指定一个key生成器
              redis-rate-limiter.replenishRate: 2 # 生成令牌的速率 每秒钟生成令牌的速率，基本上就是每秒钟允许的最大请求数量
              redis-rate-limiter.burstCapacity: 2 # 桶的容量 令牌桶的容量，就是令牌桶中存放的最大的令牌的数量
        routes:
          - id: item-service # 商品微服务
            uri: lb://item-service
            predicates:
              - Path=/item/**
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848



logging:
  level:
    com.leyou: debug